### ISSUE TITLE
json_iter.load doesn't work.

### ISSUE THREAD

**Issue by kod-kristoff** [spraakbanken/python-json-tools#8]
Sometimes misses objects.

**Comment by danr** [comment]
Hmm, do you have an example?

**Comment by kod-kristoff** [comment]
Yes, the document for 'npegl_eng.json'. It is a large file ~500000 entries and 710 Mb. I'm trying to locate the problem...

**Comment by kod-kristoff** [comment]
Fixed in v0.4.0
